apiVersion: v1
kind: Service
metadata:
  name: mcp-server-http-streamable
  namespace: mcp-server
  labels:
    app: mcp-server-http-streamable
spec:
  type: NodePort
  selector:
    app: mcp-server-http-streamable
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
